---
- name: wrapper playbook for kitchen testing "ansible-os-hardening" with custom vars for testing
  hosts: all
  become: true
  collections:
    - devsec.hardening
  tasks:
    - name: workaround for https://github.com/ansible/ansible/issues/66304
      set_fact:
        ansible_virtualization_type: "docker"
        os_env_umask: "027 #override"
    - include_role:
        name: os_hardening
    - name: verify os_env_umask
      shell:
        cmd: grep "027 #override" /etc/login.defs